version: '3'

services:
  nginx:
    build: ./requirements/nginx 
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/conf.d/
    tty: true
    stdin_open: true
