version: "3.9"

networks:
  inception_network:

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ${VOLUME_DIR}/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ${VOLUME_DIR}/mariadb
      o: bind
      type: none

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:${TAG}
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:${TAG}
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    image: mariadb:${TAG}
    env_file:
      - .env
    restart: always
